# tasks/configure_mysql.yml
- name: Install MySQL server
  ansible.builtin.package:
    name: "mysql-server-{{ mysql_version }}"
    state: present
  become: yes

- name: Stop MySQL service
  ansible.builtin.service:
    name: mysql
    state: stopped
  become: yes

- name: Move existing MySQL data to new directory
  ansible.builtin.command:
    cmd: "mv /var/lib/mysql/* {{ mysql_data_directory }}/"
    creates: "{{ mysql_data_directory }}/ibdata1"
  become: yes

- name: Update MySQL data directory permissions
  ansible.builtin.file:
    path: "{{ mysql_data_directory }}"
    owner: mysql
    group: mysql
    recurse: yes
  become: yes

- name: Update MySQL configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart MySQL
  become: yes
