# tasks/partition.yml
# Partitioning filesystem to use mysql
- name : Check /dev/vdb is formatted
  ansible.builtin.stat:
    dev : /dev/vdb
    fstype : ext4
    opts : '-F'
  when: ansible_devices['vdb'] is defined

- name: Create mount directory for MySQL data
  ansible.builtin.file:
    path: "{{ mysql_data_directory }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: Mount /dev/vdb to MySQL data directory
  ansible.builtin.mount:
    path: "{{ mysql_data_directory }}"
    src: /dev/vdb
    fstype: ext4
    opts: defaults
    state: mounted

- name: Update /etc/fstab for persistence
  ansible.builtin.mount:
    path: "{{ mysql_data_directory }}"
    src: /dev/vdb
    fstype: ext4
    opts: defaults
    state: present